### ISSUE TITLE
Generate Report

### ISSUE THREAD

**Issue by bpintel** [SRJPE/rst-pilot-app-client#232]
Creates the Generate Reports section and adds Bi-Weekly Passage Summary reporting functionality.
Associated server branch: `bi-weekly-passage-summary`

Needed front-end elements:

Setup:
- [x] Navigation
- [x] Redux

Screens:
- [x] Home screen
- [x] Share Report 
- [ ] Report complete 

Components:
- [x] Preview modal
- [x] preview content
- [x] Nav buttons
- [x] Report card

***
### 1. Query report data
  - [x] Create query for report metadata (program, program lead)
  - [ ] create queries for tables
    - [x] Historical Mean Cumulative Passage
    - [x] Passage Estimates
 
### 2. Create/generate Report 
  - [x] Create reduxSlice 
    - [x] Make Api call, 
    - Store response
      - [x] metadata
      - [x] Historical Mean Cumulative Passage
      - [ ] Passage Estimates
 - [x] Generate Word Document
   - [x] report main text
   - [ ] report table Historical Mean Cumulative Passage
   - [ ] report table Passage Estimates
 - [x] display preview of report  

### 3. Send report (email)
- [x] create email template
- [x] attach and send Report from Ipad file system

### 4. Automated schedule
- [ ] add automated email scheduling.

NEW TO DO

- [ ] Update programs dropdown to handle signed in user's programs
- [ ] update function calls to use selected program

**Comment by JordanHoang** [comment]
[Biweekly20221105-20221118.pdf](https://github.com/user-attachments/files/18871323/Biweekly20221105-20221118.pdf)

**Comment by JordanHoang** [comment]
NOTES

> Realizing some things need to be reorganized
> -need to be able to produce a complete report without contact with the client
> 
> currently the client is sending a request to the server for the required information.
> then the client side produces the word document and makes the required calculations. 
> then sends the word document to the server to be attached and sent over email.
> 
> We instead need to do more of these tasks on the server side. 
> 
> The server should be able to produce the word document and make the required calculations. 
> Then the server should be able to send the word document over email on a schedule.
> 
> We still want to initialize things on the client, and also have a report preview to display.
> so the current implementation is working but needs to be expanded on. 
> 
> the cron job needs to be able to run the report generation and email sending on a schedule.
> 
> This means that the client needs to also contain an isScheduled bool to decide if the report should be sent immediately or scheduled for later.
> 
> if the report is scheduled for later, the client should send the report to the server with the isScheduled bool set to true.
> 
> then the server needs to be able to run the report generation and email sending with the correct meta data and week range.
> 
> also the calculation for the table data needs to be done on the server side. 
> 
> This should just be the case anyway it seems


Looks like Ben was in the process of moving all of the logic from the client to the server

**Comment by JordanHoang** [comment]
![Image](https://github.com/user-attachments/assets/73fa3b89-0d0e-4ce4-8144-5cd341583b7c)


https://www.figma.com/design/uUeSkv5C4Vp3SBfIK4nk0K/RST?node-id=346-6475&p=f

**Comment by JordanHoang** [comment]
@wdwiii 

Misc
- [ ] Update programs dropdown to handle signed in user's programs
- [ ] update function calls to use selected program

**TASK 1**
- [ ] Generate word document on the server side and return to the client for testing that the document works (or save straight to machine)(or send via email)
- [ ] so invoking the `reports/bi-weekly-passage-summary/:id` should result in a workign word doc

**TASK 2**
- [ ] Task 2: once the word document is create-able , see if you can send it via email to the Email address listed in the client on "Send Report" 
- [ ] what email do we need to use? - Ideally it would be like an azure email. or datatackle domain

**TASK 3**
- [ ] if automated schedule, figure out how to do that
- [ ] store schedule params in the db (programId, reportType, frequency)
